# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sortedm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The member's name.", max_length=255, unique=True)),
                ('email', models.EmailField(help_text="The member's email address, to which messages can be sent.", max_length=254, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The rotation's name.", max_length=255, unique=True)),
                ('description', models.TextField(help_text="A description of the rotation's purpose.")),
                ('message', models.TextField(help_text='A reminder message sent to members of the rotation.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('members', sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='rotations', to='rotations.Member')),
                ('on_call', models.ForeignKey(help_text='Member currently on call.', on_delete=django.db.models.deletion.CASCADE, to='rotations.Member')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
    ]
