# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 20:40
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotation',
            name='watchers',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='watching', to='rotations.Member'),
        ),
    ]
