language: python
python:
  - '3.5'

# Route builds to Travis CI's container-based infrastructure.
sudo: false

cache: pip
install:
  - pip install -U pip
  - pip install -r requirements.txt
script: flake8 .
