web:
  build: .
  command: 'bash -c ''gunicorn rotations.wsgi --log-file -'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
    DJANGO_SETTINGS_MODULE: 'rotations.settings'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
